server:
  port: 8080


spring:
  redis:
    host: localhost
    port: 6379 #端口
    database: 0 # 数据库
    connect-timeout: 10000ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: 10000ms # 最大连接阻塞等待时间
        max-idle: 200 # 最大空闲时间
        min-idle: 5 #最小空闲连接
